/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

/* top =  1  */
/* src = "nibble_mayor_4in_synth.v:11" */
module nibble_mayor_4in_synth(NIBBLE_MAYOR, CLK, RESET_L, NIBBLES);
  /* src = "nibble_mayor_4in_synth.v:13" */
  input CLK;
  /* src = "nibble_mayor_4in_synth.v:15" */
  input [15:0] NIBBLES;
  /* src = "nibble_mayor_4in_synth.v:12" */
  output [3:0] NIBBLE_MAYOR;
  /* src = "nibble_mayor_4in_synth.v:14" */
  input RESET_L;
  assign NIBBLE_MAYOR = 4'b0000;
endmodule
