/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

/* top =  1  */
/* src = "nibble_top_synth.v:11" */
module nibble_top_synth(DATA_OUT, CLK, RESET_L, DATA_A, DATA_B, SEL_A, SEL_B, SEL_AB);
  /* src = "nibble_top_synth.v:13" */
  input CLK;
  /* src = "nibble_top_synth.v:15" */
  input [31:0] DATA_A;
  /* src = "nibble_top_synth.v:16" */
  input [31:0] DATA_B;
  /* src = "nibble_top_synth.v:12" */
  output [3:0] DATA_OUT;
  /* src = "nibble_top_synth.v:14" */
  input RESET_L;
  /* src = "nibble_top_synth.v:17" */
  input [11:0] SEL_A;
  /* src = "nibble_top_synth.v:19" */
  input [3:0] SEL_AB;
  /* src = "nibble_top_synth.v:18" */
  input [11:0] SEL_B;
  assign DATA_OUT = 4'b0000;
endmodule
