/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* src = "../NibbleMayor/bit_mayor.v:1" *)
module bit_mayor_synth(CLK, RESET_L, bm_a, bm_b, bm_selector, bm_distintos);
  (* src = "../NibbleMayor/bit_mayor.v:10" *)
  wire _00_;
  (* src = "../NibbleMayor/bit_mayor.v:10" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "../NibbleMayor/bit_mayor.v:2" *)
  input CLK;
  (* src = "../NibbleMayor/bit_mayor.v:3" *)
  input RESET_L;
  (* src = "../NibbleMayor/bit_mayor.v:4" *)
  input bm_a;
  (* src = "../NibbleMayor/bit_mayor.v:5" *)
  input bm_b;
  (* src = "../NibbleMayor/bit_mayor.v:7" *)
  output bm_distintos;
  (* src = "../NibbleMayor/bit_mayor.v:6" *)
  output bm_selector;
  INVX1 _09_ (
    .A(RESET_L),
    .Y(_07_)
  );
  INVX1 _10_ (
    .A(bm_a),
    .Y(_08_)
  );
  NAND2X1 _11_ (
    .A(bm_b),
    .B(_08_),
    .Y(_02_)
  );
  INVX1 _12_ (
    .A(bm_b),
    .Y(_03_)
  );
  NAND2X1 _13_ (
    .A(bm_a),
    .B(_03_),
    .Y(_04_)
  );
  AOI21X1 _14_ (
    .A(_02_),
    .B(_04_),
    .C(_07_),
    .Y(_00_)
  );
  INVX1 _15_ (
    .A(bm_selector),
    .Y(_05_)
  );
  OAI21X1 _16_ (
    .A(_08_),
    .B(bm_b),
    .C(RESET_L),
    .Y(_06_)
  );
  AOI21X1 _17_ (
    .A(_05_),
    .B(_02_),
    .C(_06_),
    .Y(_01_)
  );
  DFFPOSX1 _18_ (
    .CLK(CLK),
    .D(_01_),
    .Q(bm_selector)
  );
  DFFPOSX1 _19_ (
    .CLK(CLK),
    .D(_00_),
    .Q(bm_distintos)
  );
endmodule

(* src = "../NibbleMayor/nibble_mayor_2in_synth.v:3" *)
module nibble_mayor_2in_synth(CLK, RESET_L, nm2_a, nm2_b, nm2_mayor);
  (* src = "../NibbleMayor/nibble_mayor_2in_synth.v:4" *)
  input CLK;
  (* src = "../NibbleMayor/nibble_mayor_2in_synth.v:5" *)
  input RESET_L;
  (* src = "../NibbleMayor/nibble_mayor_2in_synth.v:6" *)
  input [3:0] nm2_a;
  (* src = "../NibbleMayor/nibble_mayor_2in_synth.v:7" *)
  input [3:0] nm2_b;
  (* src = "../NibbleMayor/nibble_mayor_2in_synth.v:8" *)
  output [3:0] nm2_mayor;
  assign nm2_mayor = 4'b0000;
endmodule

(* src = "../NibbleMayor/nibble_mayor_4in_synth.v:9" *)
module nibble_mayor_4in_synth(NIBBLE_MAYOR, CLK, RESET_L, NIBBLES);
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:44" *)
  wire [3:0] _0_;
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:11" *)
  input CLK;
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:13" *)
  input [15:0] NIBBLES;
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:10" *)
  output [3:0] NIBBLE_MAYOR;
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:12" *)
  input RESET_L;
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:16" *)
  wire [3:0] nm_0;
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:16" *)
  wire [3:0] nm_1;
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:15" *)
  wire [3:0] out;
  AND2X2 _1_ (
    .A(out[1]),
    .B(RESET_L),
    .Y(_0_[1])
  );
  AND2X2 _2_ (
    .A(RESET_L),
    .B(out[2]),
    .Y(_0_[2])
  );
  AND2X2 _3_ (
    .A(RESET_L),
    .B(out[3]),
    .Y(_0_[3])
  );
  AND2X2 _4_ (
    .A(RESET_L),
    .B(out[0]),
    .Y(_0_[0])
  );
  DFFPOSX1 _5_ (
    .CLK(CLK),
    .D(_0_[0]),
    .Q(NIBBLE_MAYOR[0])
  );
  DFFPOSX1 _6_ (
    .CLK(CLK),
    .D(_0_[1]),
    .Q(NIBBLE_MAYOR[1])
  );
  DFFPOSX1 _7_ (
    .CLK(CLK),
    .D(_0_[2]),
    .Q(NIBBLE_MAYOR[2])
  );
  DFFPOSX1 _8_ (
    .CLK(CLK),
    .D(_0_[3]),
    .Q(NIBBLE_MAYOR[3])
  );
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:19" *)
  nibble_mayor_2in_synth comp01 (
    .CLK(CLK),
    .RESET_L(RESET_L),
    .nm2_a(NIBBLES[3:0]),
    .nm2_b(NIBBLES[7:4]),
    .nm2_mayor(nm_0)
  );
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:27" *)
  nibble_mayor_2in_synth comp02 (
    .CLK(CLK),
    .RESET_L(RESET_L),
    .nm2_a(NIBBLES[11:8]),
    .nm2_b(NIBBLES[15:12]),
    .nm2_mayor(nm_1)
  );
  (* src = "../NibbleMayor/nibble_mayor_4in_synth.v:35" *)
  nibble_mayor_2in_synth comp03 (
    .CLK(CLK),
    .RESET_L(RESET_L),
    .nm2_a(nm_0),
    .nm2_b(nm_1),
    .nm2_mayor(out)
  );
endmodule

(* top =  1  *)
(* src = "nibble_top_synth.v:11" *)
module nibble_top_synth(DATA_OUT, CLK, RESET_L, DATA_A, DATA_B, SEL_A, SEL_B, SEL_AB);
  (* src = "nibble_top_synth.v:50" *)
  wire [3:0] _0_;
  (* src = "nibble_top_synth.v:13" *)
  input CLK;
  (* src = "nibble_top_synth.v:15" *)
  input [31:0] DATA_A;
  (* src = "nibble_top_synth.v:16" *)
  input [31:0] DATA_B;
  (* src = "nibble_top_synth.v:12" *)
  output [3:0] DATA_OUT;
  (* src = "nibble_top_synth.v:25" *)
  wire [15:0] NIBBLES;
  (* src = "nibble_top_synth.v:26" *)
  wire [3:0] NIBBLE_MAYOR;
  (* src = "nibble_top_synth.v:14" *)
  input RESET_L;
  (* src = "nibble_top_synth.v:17" *)
  input [11:0] SEL_A;
  (* src = "nibble_top_synth.v:19" *)
  input [3:0] SEL_AB;
  (* src = "nibble_top_synth.v:18" *)
  input [11:0] SEL_B;
  AND2X2 _1_ (
    .A(NIBBLE_MAYOR[1]),
    .B(RESET_L),
    .Y(_0_[1])
  );
  AND2X2 _2_ (
    .A(RESET_L),
    .B(NIBBLE_MAYOR[2]),
    .Y(_0_[2])
  );
  AND2X2 _3_ (
    .A(RESET_L),
    .B(NIBBLE_MAYOR[3]),
    .Y(_0_[3])
  );
  AND2X2 _4_ (
    .A(RESET_L),
    .B(NIBBLE_MAYOR[0]),
    .Y(_0_[0])
  );
  DFFPOSX1 _5_ (
    .CLK(CLK),
    .D(_0_[0]),
    .Q(DATA_OUT[0])
  );
  DFFPOSX1 _6_ (
    .CLK(CLK),
    .D(_0_[1]),
    .Q(DATA_OUT[1])
  );
  DFFPOSX1 _7_ (
    .CLK(CLK),
    .D(_0_[2]),
    .Q(DATA_OUT[2])
  );
  DFFPOSX1 _8_ (
    .CLK(CLK),
    .D(_0_[3]),
    .Q(DATA_OUT[3])
  );
  (* src = "nibble_top_synth.v:30" *)
  selector4_synth logica_seleccion (
    .CLK(CLK),
    .DATA_A(DATA_A),
    .DATA_B(DATA_B),
    .NIBBLES(NIBBLES),
    .RESET_L(RESET_L),
    .SEL_A(SEL_A),
    .SEL_AB(SEL_AB),
    .SEL_B(SEL_B)
  );
  (* src = "nibble_top_synth.v:41" *)
  nibble_mayor_4in_synth nibble_mayor (
    .CLK(CLK),
    .NIBBLES(NIBBLES),
    .NIBBLE_MAYOR(NIBBLE_MAYOR),
    .RESET_L(RESET_L)
  );
endmodule

(* src = "../Selector/selector4_synth.v:30" *)
module selector_synth(dataA, dataB, selA, selB, sel, reset_L, clk, nibbleOut);
  (* src = "../Selector/selector4_synth.v:41" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  (* src = "../Selector/selector4_synth.v:37" *)
  input clk;
  (* src = "../Selector/selector4_synth.v:31" *)
  input [31:0] dataA;
  (* src = "../Selector/selector4_synth.v:32" *)
  input [31:0] dataB;
  (* src = "../Selector/selector4_synth.v:38" *)
  output [3:0] nibbleOut;
  (* src = "../Selector/selector4_synth.v:36" *)
  input reset_L;
  (* src = "../Selector/selector4_synth.v:35" *)
  input sel;
  (* src = "../Selector/selector4_synth.v:33" *)
  input [2:0] selA;
  (* src = "../Selector/selector4_synth.v:34" *)
  input [2:0] selB;
  INVX1 _135_ (
    .A(reset_L),
    .Y(_112_)
  );
  INVX1 _136_ (
    .A(selA[1]),
    .Y(_113_)
  );
  INVX1 _137_ (
    .A(selA[2]),
    .Y(_114_)
  );
  INVX1 _138_ (
    .A(dataA[16]),
    .Y(_115_)
  );
  NAND2X1 _139_ (
    .A(dataA[20]),
    .B(selA[0]),
    .Y(_116_)
  );
  OAI21X1 _140_ (
    .A(_115_),
    .B(selA[0]),
    .C(_116_),
    .Y(_117_)
  );
  INVX1 _141_ (
    .A(dataA[0]),
    .Y(_118_)
  );
  AOI21X1 _142_ (
    .A(dataA[4]),
    .B(selA[0]),
    .C(selA[2]),
    .Y(_119_)
  );
  OAI21X1 _143_ (
    .A(_118_),
    .B(selA[0]),
    .C(_119_),
    .Y(_120_)
  );
  OAI21X1 _144_ (
    .A(_117_),
    .B(_114_),
    .C(_120_),
    .Y(_121_)
  );
  NAND2X1 _145_ (
    .A(_113_),
    .B(_121_),
    .Y(_122_)
  );
  INVX1 _146_ (
    .A(dataA[24]),
    .Y(_123_)
  );
  NAND2X1 _147_ (
    .A(dataA[28]),
    .B(selA[0]),
    .Y(_124_)
  );
  OAI21X1 _148_ (
    .A(_123_),
    .B(selA[0]),
    .C(_124_),
    .Y(_125_)
  );
  INVX1 _149_ (
    .A(dataA[8]),
    .Y(_126_)
  );
  AOI21X1 _150_ (
    .A(dataA[12]),
    .B(selA[0]),
    .C(selA[2]),
    .Y(_127_)
  );
  OAI21X1 _151_ (
    .A(_126_),
    .B(selA[0]),
    .C(_127_),
    .Y(_128_)
  );
  OAI21X1 _152_ (
    .A(_125_),
    .B(_114_),
    .C(_128_),
    .Y(_129_)
  );
  AOI21X1 _153_ (
    .A(selA[1]),
    .B(_129_),
    .C(sel),
    .Y(_130_)
  );
  NAND2X1 _154_ (
    .A(_122_),
    .B(_130_),
    .Y(_131_)
  );
  INVX1 _155_ (
    .A(selB[1]),
    .Y(_132_)
  );
  INVX1 _156_ (
    .A(selB[2]),
    .Y(_133_)
  );
  INVX1 _157_ (
    .A(dataB[20]),
    .Y(_134_)
  );
  AOI21X1 _158_ (
    .A(selB[0]),
    .B(_134_),
    .C(_133_),
    .Y(_001_)
  );
  OAI21X1 _159_ (
    .A(dataB[16]),
    .B(selB[0]),
    .C(_001_),
    .Y(_002_)
  );
  INVX1 _160_ (
    .A(dataB[4]),
    .Y(_003_)
  );
  AOI21X1 _161_ (
    .A(selB[0]),
    .B(_003_),
    .C(selB[2]),
    .Y(_004_)
  );
  OAI21X1 _162_ (
    .A(dataB[0]),
    .B(selB[0]),
    .C(_004_),
    .Y(_005_)
  );
  NAND3X1 _163_ (
    .A(_132_),
    .B(_002_),
    .C(_005_),
    .Y(_006_)
  );
  INVX1 _164_ (
    .A(dataB[12]),
    .Y(_007_)
  );
  AOI21X1 _165_ (
    .A(selB[0]),
    .B(_007_),
    .C(selB[2]),
    .Y(_008_)
  );
  OAI21X1 _166_ (
    .A(dataB[8]),
    .B(selB[0]),
    .C(_008_),
    .Y(_009_)
  );
  INVX1 _167_ (
    .A(dataB[28]),
    .Y(_010_)
  );
  AOI21X1 _168_ (
    .A(selB[0]),
    .B(_010_),
    .C(_133_),
    .Y(_011_)
  );
  OAI21X1 _169_ (
    .A(dataB[24]),
    .B(selB[0]),
    .C(_011_),
    .Y(_012_)
  );
  NAND3X1 _170_ (
    .A(selB[1]),
    .B(_009_),
    .C(_012_),
    .Y(_013_)
  );
  NAND3X1 _171_ (
    .A(sel),
    .B(_006_),
    .C(_013_),
    .Y(_014_)
  );
  AOI21X1 _172_ (
    .A(_014_),
    .B(_131_),
    .C(_112_),
    .Y(_000_[0])
  );
  INVX1 _173_ (
    .A(sel),
    .Y(_015_)
  );
  INVX1 _174_ (
    .A(dataA[17]),
    .Y(_016_)
  );
  OAI21X1 _175_ (
    .A(_016_),
    .B(selA[0]),
    .C(selA[2]),
    .Y(_017_)
  );
  AOI21X1 _176_ (
    .A(dataA[21]),
    .B(selA[0]),
    .C(_017_),
    .Y(_018_)
  );
  INVX1 _177_ (
    .A(dataA[1]),
    .Y(_019_)
  );
  NOR2X1 _178_ (
    .A(selA[0]),
    .B(_019_),
    .Y(_020_)
  );
  NAND2X1 _179_ (
    .A(dataA[5]),
    .B(selA[0]),
    .Y(_021_)
  );
  NAND2X1 _180_ (
    .A(_114_),
    .B(_021_),
    .Y(_022_)
  );
  OAI21X1 _181_ (
    .A(_022_),
    .B(_020_),
    .C(_113_),
    .Y(_023_)
  );
  INVX1 _182_ (
    .A(dataA[25]),
    .Y(_024_)
  );
  OAI21X1 _183_ (
    .A(_024_),
    .B(selA[0]),
    .C(selA[2]),
    .Y(_025_)
  );
  AOI21X1 _184_ (
    .A(dataA[29]),
    .B(selA[0]),
    .C(_025_),
    .Y(_026_)
  );
  INVX1 _185_ (
    .A(dataA[9]),
    .Y(_027_)
  );
  AOI21X1 _186_ (
    .A(dataA[13]),
    .B(selA[0]),
    .C(selA[2]),
    .Y(_028_)
  );
  OAI21X1 _187_ (
    .A(_027_),
    .B(selA[0]),
    .C(_028_),
    .Y(_029_)
  );
  NAND2X1 _188_ (
    .A(selA[1]),
    .B(_029_),
    .Y(_030_)
  );
  OAI22X1 _189_ (
    .A(_023_),
    .B(_018_),
    .C(_026_),
    .D(_030_),
    .Y(_031_)
  );
  NAND2X1 _190_ (
    .A(_015_),
    .B(_031_),
    .Y(_032_)
  );
  INVX1 _191_ (
    .A(dataB[29]),
    .Y(_033_)
  );
  AOI21X1 _192_ (
    .A(selB[0]),
    .B(_033_),
    .C(_133_),
    .Y(_034_)
  );
  OAI21X1 _193_ (
    .A(dataB[25]),
    .B(selB[0]),
    .C(_034_),
    .Y(_035_)
  );
  INVX1 _194_ (
    .A(dataB[13]),
    .Y(_036_)
  );
  AOI21X1 _195_ (
    .A(selB[0]),
    .B(_036_),
    .C(selB[2]),
    .Y(_037_)
  );
  OAI21X1 _196_ (
    .A(dataB[9]),
    .B(selB[0]),
    .C(_037_),
    .Y(_038_)
  );
  NAND3X1 _197_ (
    .A(selB[1]),
    .B(_035_),
    .C(_038_),
    .Y(_039_)
  );
  INVX1 _198_ (
    .A(dataB[5]),
    .Y(_040_)
  );
  AOI21X1 _199_ (
    .A(selB[0]),
    .B(_040_),
    .C(selB[2]),
    .Y(_041_)
  );
  OAI21X1 _200_ (
    .A(dataB[1]),
    .B(selB[0]),
    .C(_041_),
    .Y(_042_)
  );
  INVX1 _201_ (
    .A(dataB[21]),
    .Y(_043_)
  );
  AOI21X1 _202_ (
    .A(selB[0]),
    .B(_043_),
    .C(_133_),
    .Y(_044_)
  );
  OAI21X1 _203_ (
    .A(dataB[17]),
    .B(selB[0]),
    .C(_044_),
    .Y(_045_)
  );
  NAND3X1 _204_ (
    .A(_132_),
    .B(_042_),
    .C(_045_),
    .Y(_046_)
  );
  NAND3X1 _205_ (
    .A(sel),
    .B(_039_),
    .C(_046_),
    .Y(_047_)
  );
  AOI21X1 _206_ (
    .A(_047_),
    .B(_032_),
    .C(_112_),
    .Y(_000_[1])
  );
  INVX1 _207_ (
    .A(dataA[18]),
    .Y(_048_)
  );
  NAND2X1 _208_ (
    .A(dataA[22]),
    .B(selA[0]),
    .Y(_049_)
  );
  OAI21X1 _209_ (
    .A(_048_),
    .B(selA[0]),
    .C(_049_),
    .Y(_050_)
  );
  INVX1 _210_ (
    .A(dataA[2]),
    .Y(_051_)
  );
  AOI21X1 _211_ (
    .A(dataA[6]),
    .B(selA[0]),
    .C(selA[2]),
    .Y(_052_)
  );
  OAI21X1 _212_ (
    .A(_051_),
    .B(selA[0]),
    .C(_052_),
    .Y(_053_)
  );
  OAI21X1 _213_ (
    .A(_050_),
    .B(_114_),
    .C(_053_),
    .Y(_054_)
  );
  NAND2X1 _214_ (
    .A(_113_),
    .B(_054_),
    .Y(_055_)
  );
  INVX1 _215_ (
    .A(dataA[26]),
    .Y(_056_)
  );
  NAND2X1 _216_ (
    .A(dataA[30]),
    .B(selA[0]),
    .Y(_057_)
  );
  OAI21X1 _217_ (
    .A(_056_),
    .B(selA[0]),
    .C(_057_),
    .Y(_058_)
  );
  INVX1 _218_ (
    .A(dataA[10]),
    .Y(_059_)
  );
  AOI21X1 _219_ (
    .A(dataA[14]),
    .B(selA[0]),
    .C(selA[2]),
    .Y(_060_)
  );
  OAI21X1 _220_ (
    .A(_059_),
    .B(selA[0]),
    .C(_060_),
    .Y(_061_)
  );
  OAI21X1 _221_ (
    .A(_058_),
    .B(_114_),
    .C(_061_),
    .Y(_062_)
  );
  NAND2X1 _222_ (
    .A(selA[1]),
    .B(_062_),
    .Y(_063_)
  );
  NAND3X1 _223_ (
    .A(_015_),
    .B(_055_),
    .C(_063_),
    .Y(_064_)
  );
  INVX1 _224_ (
    .A(dataB[30]),
    .Y(_065_)
  );
  AOI21X1 _225_ (
    .A(selB[0]),
    .B(_065_),
    .C(_133_),
    .Y(_066_)
  );
  OAI21X1 _226_ (
    .A(dataB[26]),
    .B(selB[0]),
    .C(_066_),
    .Y(_067_)
  );
  INVX1 _227_ (
    .A(dataB[14]),
    .Y(_068_)
  );
  AOI21X1 _228_ (
    .A(selB[0]),
    .B(_068_),
    .C(selB[2]),
    .Y(_069_)
  );
  OAI21X1 _229_ (
    .A(dataB[10]),
    .B(selB[0]),
    .C(_069_),
    .Y(_070_)
  );
  NAND3X1 _230_ (
    .A(selB[1]),
    .B(_067_),
    .C(_070_),
    .Y(_071_)
  );
  INVX1 _231_ (
    .A(dataB[6]),
    .Y(_072_)
  );
  AOI21X1 _232_ (
    .A(selB[0]),
    .B(_072_),
    .C(selB[2]),
    .Y(_073_)
  );
  OAI21X1 _233_ (
    .A(dataB[2]),
    .B(selB[0]),
    .C(_073_),
    .Y(_074_)
  );
  INVX1 _234_ (
    .A(dataB[22]),
    .Y(_075_)
  );
  AOI21X1 _235_ (
    .A(selB[0]),
    .B(_075_),
    .C(_133_),
    .Y(_076_)
  );
  OAI21X1 _236_ (
    .A(dataB[18]),
    .B(selB[0]),
    .C(_076_),
    .Y(_077_)
  );
  NAND3X1 _237_ (
    .A(_132_),
    .B(_074_),
    .C(_077_),
    .Y(_078_)
  );
  NAND3X1 _238_ (
    .A(sel),
    .B(_071_),
    .C(_078_),
    .Y(_079_)
  );
  AOI21X1 _239_ (
    .A(_064_),
    .B(_079_),
    .C(_112_),
    .Y(_000_[2])
  );
  INVX1 _240_ (
    .A(dataA[19]),
    .Y(_080_)
  );
  NAND2X1 _241_ (
    .A(dataA[23]),
    .B(selA[0]),
    .Y(_081_)
  );
  OAI21X1 _242_ (
    .A(_080_),
    .B(selA[0]),
    .C(_081_),
    .Y(_082_)
  );
  INVX1 _243_ (
    .A(dataA[3]),
    .Y(_083_)
  );
  AOI21X1 _244_ (
    .A(dataA[7]),
    .B(selA[0]),
    .C(selA[2]),
    .Y(_084_)
  );
  OAI21X1 _245_ (
    .A(_083_),
    .B(selA[0]),
    .C(_084_),
    .Y(_085_)
  );
  OAI21X1 _246_ (
    .A(_082_),
    .B(_114_),
    .C(_085_),
    .Y(_086_)
  );
  NAND2X1 _247_ (
    .A(_113_),
    .B(_086_),
    .Y(_087_)
  );
  INVX1 _248_ (
    .A(dataA[27]),
    .Y(_088_)
  );
  NAND2X1 _249_ (
    .A(dataA[31]),
    .B(selA[0]),
    .Y(_089_)
  );
  OAI21X1 _250_ (
    .A(_088_),
    .B(selA[0]),
    .C(_089_),
    .Y(_090_)
  );
  INVX1 _251_ (
    .A(dataA[11]),
    .Y(_091_)
  );
  AOI21X1 _252_ (
    .A(dataA[15]),
    .B(selA[0]),
    .C(selA[2]),
    .Y(_092_)
  );
  OAI21X1 _253_ (
    .A(_091_),
    .B(selA[0]),
    .C(_092_),
    .Y(_093_)
  );
  OAI21X1 _254_ (
    .A(_090_),
    .B(_114_),
    .C(_093_),
    .Y(_094_)
  );
  NAND2X1 _255_ (
    .A(selA[1]),
    .B(_094_),
    .Y(_095_)
  );
  NAND3X1 _256_ (
    .A(_015_),
    .B(_087_),
    .C(_095_),
    .Y(_096_)
  );
  INVX1 _257_ (
    .A(dataB[31]),
    .Y(_097_)
  );
  AOI21X1 _258_ (
    .A(selB[0]),
    .B(_097_),
    .C(_133_),
    .Y(_098_)
  );
  OAI21X1 _259_ (
    .A(dataB[27]),
    .B(selB[0]),
    .C(_098_),
    .Y(_099_)
  );
  INVX1 _260_ (
    .A(dataB[15]),
    .Y(_100_)
  );
  AOI21X1 _261_ (
    .A(selB[0]),
    .B(_100_),
    .C(selB[2]),
    .Y(_101_)
  );
  OAI21X1 _262_ (
    .A(dataB[11]),
    .B(selB[0]),
    .C(_101_),
    .Y(_102_)
  );
  NAND3X1 _263_ (
    .A(selB[1]),
    .B(_099_),
    .C(_102_),
    .Y(_103_)
  );
  INVX1 _264_ (
    .A(dataB[7]),
    .Y(_104_)
  );
  AOI21X1 _265_ (
    .A(selB[0]),
    .B(_104_),
    .C(selB[2]),
    .Y(_105_)
  );
  OAI21X1 _266_ (
    .A(dataB[3]),
    .B(selB[0]),
    .C(_105_),
    .Y(_106_)
  );
  INVX1 _267_ (
    .A(dataB[23]),
    .Y(_107_)
  );
  AOI21X1 _268_ (
    .A(selB[0]),
    .B(_107_),
    .C(_133_),
    .Y(_108_)
  );
  OAI21X1 _269_ (
    .A(dataB[19]),
    .B(selB[0]),
    .C(_108_),
    .Y(_109_)
  );
  NAND3X1 _270_ (
    .A(_132_),
    .B(_106_),
    .C(_109_),
    .Y(_110_)
  );
  NAND3X1 _271_ (
    .A(sel),
    .B(_103_),
    .C(_110_),
    .Y(_111_)
  );
  AOI21X1 _272_ (
    .A(_096_),
    .B(_111_),
    .C(_112_),
    .Y(_000_[3])
  );
  DFFPOSX1 _273_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(nibbleOut[0])
  );
  DFFPOSX1 _274_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(nibbleOut[1])
  );
  DFFPOSX1 _275_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(nibbleOut[2])
  );
  DFFPOSX1 _276_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(nibbleOut[3])
  );
endmodule

(* src = "../Selector/selector4_synth.v:5" *)
module selector4_synth(NIBBLES, DATA_A, DATA_B, SEL_A, SEL_B, SEL_AB, RESET_L, CLK);
  (* src = "../Selector/selector4_synth.v:12" *)
  input CLK;
  (* src = "../Selector/selector4_synth.v:6" *)
  input [31:0] DATA_A;
  (* src = "../Selector/selector4_synth.v:7" *)
  input [31:0] DATA_B;
  (* src = "../Selector/selector4_synth.v:5" *)
  output [15:0] NIBBLES;
  (* src = "../Selector/selector4_synth.v:11" *)
  input RESET_L;
  (* src = "../Selector/selector4_synth.v:8" *)
  input [11:0] SEL_A;
  (* src = "../Selector/selector4_synth.v:10" *)
  input [3:0] SEL_AB;
  (* src = "../Selector/selector4_synth.v:9" *)
  input [11:0] SEL_B;
  (* src = "../Selector/selector4_synth.v:17" *)
  selector_synth \selectores[0].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(NIBBLES[3:0]),
    .reset_L(RESET_L),
    .sel(SEL_AB[0]),
    .selA(SEL_A[2:0]),
    .selB(SEL_B[2:0])
  );
  (* src = "../Selector/selector4_synth.v:17" *)
  selector_synth \selectores[1].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(NIBBLES[7:4]),
    .reset_L(RESET_L),
    .sel(SEL_AB[1]),
    .selA(SEL_A[5:3]),
    .selB(SEL_B[5:3])
  );
  (* src = "../Selector/selector4_synth.v:17" *)
  selector_synth \selectores[2].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(NIBBLES[11:8]),
    .reset_L(RESET_L),
    .sel(SEL_AB[2]),
    .selA(SEL_A[8:6]),
    .selB(SEL_B[8:6])
  );
  (* src = "../Selector/selector4_synth.v:17" *)
  selector_synth \selectores[3].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(NIBBLES[15:12]),
    .reset_L(RESET_L),
    .sel(SEL_AB[3]),
    .selA(SEL_A[11:9]),
    .selB(SEL_B[11:9])
  );
endmodule
