/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "selector.v:1" *)
module selector(dataA, dataB, selA, selB, sel, reset_L, clk, nibbleOut);
  (* src = "selector.v:12" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  (* src = "selector.v:16|<techmap.v>:142" *)
  wire [95:0] _286_;
  (* src = "selector.v:16|<techmap.v>:142" *)
  wire [95:0] _287_;
  (* src = "selector.v:16|<techmap.v>:145" *)
  wire [95:0] _288_;
  (* src = "selector.v:16|<techmap.v>:145" *)
  wire [95:0] _289_;
  (* src = "selector.v:16|<techmap.v>:145" *)
  wire [95:0] _290_;
  (* src = "selector.v:16|<techmap.v>:145" *)
  wire [95:0] _291_;
  (* src = "selector.v:16|<techmap.v>:145" *)
  wire [95:0] _292_;
  (* src = "selector.v:16|<techmap.v>:145" *)
  wire [95:0] _293_;
  (* src = "selector.v:16" *)
  wire [3:0] _294_;
  (* src = "selector.v:8" *)
  input clk;
  (* src = "selector.v:2" *)
  input [31:0] dataA;
  (* src = "selector.v:3" *)
  input [31:0] dataB;
  (* src = "selector.v:9" *)
  output [3:0] nibbleOut;
  (* src = "selector.v:7" *)
  input reset_L;
  (* src = "selector.v:6" *)
  input sel;
  (* src = "selector.v:4" *)
  input [2:0] selA;
  (* src = "selector.v:5" *)
  input [2:0] selB;
  NOR _295_ (
    .A(_119_),
    .B(_115_),
    .Y(_120_)
  );
  NAND _296_ (
    .A(_120_),
    .B(_117_),
    .Y(_121_)
  );
  NAND _297_ (
    .A(_121_),
    .B(_258_),
    .Y(_122_)
  );
  NOR _298_ (
    .A(_122_),
    .B(_116_),
    .Y(_123_)
  );
  NOT _299_ (
    .A(_234_),
    .Y(_124_)
  );
  NOR _300_ (
    .A(_245_),
    .B(_124_),
    .Y(_125_)
  );
  NAND _301_ (
    .A(_245_),
    .B(_242_),
    .Y(_127_)
  );
  NAND _302_ (
    .A(_127_),
    .B(_115_),
    .Y(_128_)
  );
  NOR _303_ (
    .A(_128_),
    .B(_125_),
    .Y(_129_)
  );
  NAND _304_ (
    .A(_260_),
    .B(_233_),
    .Y(_130_)
  );
  NOT _305_ (
    .A(_241_),
    .Y(_131_)
  );
  NOR _306_ (
    .A(_260_),
    .B(_131_),
    .Y(_132_)
  );
  NOR _307_ (
    .A(_132_),
    .B(_115_),
    .Y(_133_)
  );
  NAND _308_ (
    .A(_133_),
    .B(_130_),
    .Y(_134_)
  );
  NAND _309_ (
    .A(_134_),
    .B(_246_),
    .Y(_135_)
  );
  NOR _310_ (
    .A(_135_),
    .B(_129_),
    .Y(_136_)
  );
  NOR _311_ (
    .A(_136_),
    .B(_123_),
    .Y(_138_)
  );
  NOR _312_ (
    .A(_138_),
    .B(_126_),
    .Y(_139_)
  );
  NAND _313_ (
    .A(_279_),
    .B(_012_),
    .Y(_140_)
  );
  NAND _314_ (
    .A(_281_),
    .B(_251_),
    .Y(_141_)
  );
  NAND _315_ (
    .A(_141_),
    .B(_140_),
    .Y(_142_)
  );
  NAND _316_ (
    .A(_142_),
    .B(_047_),
    .Y(_143_)
  );
  NAND _317_ (
    .A(_259_),
    .B(_012_),
    .Y(_144_)
  );
  NAND _318_ (
    .A(_261_),
    .B(_251_),
    .Y(_145_)
  );
  NAND _319_ (
    .A(_145_),
    .B(_144_),
    .Y(_146_)
  );
  NAND _320_ (
    .A(_146_),
    .B(_020_),
    .Y(_147_)
  );
  NAND _321_ (
    .A(_147_),
    .B(_143_),
    .Y(_149_)
  );
  NOR _322_ (
    .A(_149_),
    .B(_056_),
    .Y(_150_)
  );
  NOR _323_ (
    .A(_047_),
    .B(_014_),
    .Y(_151_)
  );
  NOT _324_ (
    .A(_035_),
    .Y(_152_)
  );
  NAND _325_ (
    .A(_047_),
    .B(_152_),
    .Y(_153_)
  );
  NAND _326_ (
    .A(_153_),
    .B(_012_),
    .Y(_154_)
  );
  NOR _327_ (
    .A(_154_),
    .B(_151_),
    .Y(_155_)
  );
  NOR _328_ (
    .A(_020_),
    .B(_037_),
    .Y(_156_)
  );
  NOT _329_ (
    .A(_016_),
    .Y(_157_)
  );
  NAND _330_ (
    .A(_020_),
    .B(_157_),
    .Y(_158_)
  );
  NAND _331_ (
    .A(_158_),
    .B(_251_),
    .Y(_159_)
  );
  NOR _332_ (
    .A(_159_),
    .B(_156_),
    .Y(_160_)
  );
  NOR _333_ (
    .A(_160_),
    .B(_155_),
    .Y(_161_)
  );
  NAND _334_ (
    .A(_161_),
    .B(_056_),
    .Y(_162_)
  );
  NAND _335_ (
    .A(_162_),
    .B(_126_),
    .Y(_163_)
  );
  NOR _336_ (
    .A(_163_),
    .B(_150_),
    .Y(_164_)
  );
  NOR _337_ (
    .A(_164_),
    .B(_139_),
    .Y(_165_)
  );
  NOR _338_ (
    .A(_165_),
    .B(_248_),
    .Y(_072_)
  );
  NOT _339_ (
    .A(_211_),
    .Y(_166_)
  );
  NOR _340_ (
    .A(_245_),
    .B(_166_),
    .Y(_167_)
  );
  NAND _341_ (
    .A(_245_),
    .B(_228_),
    .Y(_169_)
  );
  NAND _342_ (
    .A(_169_),
    .B(_115_),
    .Y(_170_)
  );
  NOR _343_ (
    .A(_170_),
    .B(_167_),
    .Y(_171_)
  );
  NAND _344_ (
    .A(_260_),
    .B(_200_),
    .Y(_172_)
  );
  NOT _345_ (
    .A(_227_),
    .Y(_173_)
  );
  NOR _346_ (
    .A(_260_),
    .B(_173_),
    .Y(_174_)
  );
  NOR _347_ (
    .A(_174_),
    .B(_115_),
    .Y(_175_)
  );
  NAND _348_ (
    .A(_175_),
    .B(_172_),
    .Y(_176_)
  );
  NAND _349_ (
    .A(_176_),
    .B(_258_),
    .Y(_177_)
  );
  NOR _350_ (
    .A(_177_),
    .B(_171_),
    .Y(_178_)
  );
  NOT _351_ (
    .A(_236_),
    .Y(_180_)
  );
  NOR _352_ (
    .A(_245_),
    .B(_180_),
    .Y(_181_)
  );
  NAND _353_ (
    .A(_245_),
    .B(_244_),
    .Y(_182_)
  );
  NAND _354_ (
    .A(_182_),
    .B(_115_),
    .Y(_183_)
  );
  NOR _355_ (
    .A(_183_),
    .B(_181_),
    .Y(_184_)
  );
  NAND _356_ (
    .A(_260_),
    .B(_235_),
    .Y(_185_)
  );
  NOT _357_ (
    .A(_243_),
    .Y(_186_)
  );
  NOR _358_ (
    .A(_260_),
    .B(_186_),
    .Y(_187_)
  );
  NOR _359_ (
    .A(_187_),
    .B(_115_),
    .Y(_188_)
  );
  NAND _360_ (
    .A(_188_),
    .B(_185_),
    .Y(_189_)
  );
  NAND _361_ (
    .A(_189_),
    .B(_246_),
    .Y(_190_)
  );
  NOR _362_ (
    .A(_190_),
    .B(_184_),
    .Y(_191_)
  );
  NOR _363_ (
    .A(_191_),
    .B(_178_),
    .Y(_192_)
  );
  NOR _364_ (
    .A(_192_),
    .B(_126_),
    .Y(_193_)
  );
  NAND _365_ (
    .A(_284_),
    .B(_012_),
    .Y(_194_)
  );
  NAND _366_ (
    .A(_001_),
    .B(_251_),
    .Y(_195_)
  );
  NAND _367_ (
    .A(_195_),
    .B(_194_),
    .Y(_196_)
  );
  NAND _368_ (
    .A(_196_),
    .B(_047_),
    .Y(_197_)
  );
  NAND _369_ (
    .A(_264_),
    .B(_012_),
    .Y(_198_)
  );
  NAND _370_ (
    .A(_266_),
    .B(_251_),
    .Y(_199_)
  );
  NAND _371_ (
    .A(_199_),
    .B(_198_),
    .Y(_201_)
  );
  NAND _372_ (
    .A(_201_),
    .B(_020_),
    .Y(_202_)
  );
  NAND _373_ (
    .A(_202_),
    .B(_197_),
    .Y(_203_)
  );
  NOR _374_ (
    .A(_203_),
    .B(_056_),
    .Y(_204_)
  );
  NOR _375_ (
    .A(_047_),
    .B(_019_),
    .Y(_205_)
  );
  NOT _376_ (
    .A(_040_),
    .Y(_206_)
  );
  NAND _377_ (
    .A(_047_),
    .B(_206_),
    .Y(_207_)
  );
  NAND _378_ (
    .A(_207_),
    .B(_012_),
    .Y(_208_)
  );
  NOR _379_ (
    .A(_208_),
    .B(_205_),
    .Y(_209_)
  );
  NOR _380_ (
    .A(_020_),
    .B(_042_),
    .Y(_210_)
  );
  NOT _381_ (
    .A(_021_),
    .Y(_212_)
  );
  NAND _382_ (
    .A(_020_),
    .B(_212_),
    .Y(_213_)
  );
  NAND _383_ (
    .A(_213_),
    .B(_251_),
    .Y(_214_)
  );
  NOR _384_ (
    .A(_214_),
    .B(_210_),
    .Y(_215_)
  );
  NOR _385_ (
    .A(_215_),
    .B(_209_),
    .Y(_216_)
  );
  NAND _386_ (
    .A(_216_),
    .B(_056_),
    .Y(_217_)
  );
  NAND _387_ (
    .A(_217_),
    .B(_126_),
    .Y(_218_)
  );
  NOR _388_ (
    .A(_218_),
    .B(_204_),
    .Y(_219_)
  );
  NOR _389_ (
    .A(_219_),
    .B(_193_),
    .Y(_220_)
  );
  NOR _390_ (
    .A(_220_),
    .B(_248_),
    .Y(_083_)
  );
  NOT _391_ (
    .A(_034_),
    .Y(_248_)
  );
  NOT _392_ (
    .A(_105_),
    .Y(_250_)
  );
  NOR _393_ (
    .A(_245_),
    .B(_250_),
    .Y(_252_)
  );
  NAND _394_ (
    .A(_245_),
    .B(_222_),
    .Y(_253_)
  );
  NAND _395_ (
    .A(_253_),
    .B(_115_),
    .Y(_255_)
  );
  NOR _396_ (
    .A(_255_),
    .B(_252_),
    .Y(_257_)
  );
  NOT _397_ (
    .A(_246_),
    .Y(_258_)
  );
  NOT _398_ (
    .A(_245_),
    .Y(_260_)
  );
  NAND _399_ (
    .A(_260_),
    .B(_094_),
    .Y(_262_)
  );
  NOT _400_ (
    .A(_221_),
    .Y(_263_)
  );
  NOR _401_ (
    .A(_260_),
    .B(_263_),
    .Y(_265_)
  );
  NOR _402_ (
    .A(_265_),
    .B(_115_),
    .Y(_267_)
  );
  NAND _403_ (
    .A(_267_),
    .B(_262_),
    .Y(_268_)
  );
  NAND _404_ (
    .A(_268_),
    .B(_258_),
    .Y(_270_)
  );
  NOR _405_ (
    .A(_270_),
    .B(_257_),
    .Y(_272_)
  );
  NOT _406_ (
    .A(_230_),
    .Y(_273_)
  );
  NOR _407_ (
    .A(_245_),
    .B(_273_),
    .Y(_275_)
  );
  NAND _408_ (
    .A(_245_),
    .B(_238_),
    .Y(_277_)
  );
  NAND _409_ (
    .A(_277_),
    .B(_115_),
    .Y(_278_)
  );
  NOR _410_ (
    .A(_278_),
    .B(_275_),
    .Y(_280_)
  );
  NAND _411_ (
    .A(_260_),
    .B(_229_),
    .Y(_282_)
  );
  NOT _412_ (
    .A(_237_),
    .Y(_283_)
  );
  NOR _413_ (
    .A(_260_),
    .B(_283_),
    .Y(_285_)
  );
  NOR _414_ (
    .A(_285_),
    .B(_115_),
    .Y(_002_)
  );
  NAND _415_ (
    .A(_002_),
    .B(_282_),
    .Y(_003_)
  );
  NAND _416_ (
    .A(_003_),
    .B(_246_),
    .Y(_005_)
  );
  NOR _417_ (
    .A(_005_),
    .B(_280_),
    .Y(_007_)
  );
  NOR _418_ (
    .A(_007_),
    .B(_272_),
    .Y(_008_)
  );
  NOR _419_ (
    .A(_008_),
    .B(_126_),
    .Y(_010_)
  );
  NOT _420_ (
    .A(_251_),
    .Y(_012_)
  );
  NAND _421_ (
    .A(_269_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _422_ (
    .A(_271_),
    .B(_251_),
    .Y(_015_)
  );
  NAND _423_ (
    .A(_015_),
    .B(_013_),
    .Y(_017_)
  );
  NAND _424_ (
    .A(_017_),
    .B(_047_),
    .Y(_018_)
  );
  NOT _425_ (
    .A(_047_),
    .Y(_020_)
  );
  NAND _426_ (
    .A(_012_),
    .B(_247_),
    .Y(_022_)
  );
  NAND _427_ (
    .A(_251_),
    .B(_249_),
    .Y(_023_)
  );
  NAND _428_ (
    .A(_023_),
    .B(_022_),
    .Y(_025_)
  );
  NAND _429_ (
    .A(_025_),
    .B(_020_),
    .Y(_027_)
  );
  NAND _430_ (
    .A(_027_),
    .B(_018_),
    .Y(_028_)
  );
  NOR _431_ (
    .A(_028_),
    .B(_056_),
    .Y(_030_)
  );
  NOR _432_ (
    .A(_047_),
    .B(_004_),
    .Y(_032_)
  );
  NOT _433_ (
    .A(_024_),
    .Y(_033_)
  );
  NAND _434_ (
    .A(_047_),
    .B(_033_),
    .Y(_036_)
  );
  NAND _435_ (
    .A(_036_),
    .B(_012_),
    .Y(_038_)
  );
  NOR _436_ (
    .A(_038_),
    .B(_032_),
    .Y(_039_)
  );
  NOR _437_ (
    .A(_020_),
    .B(_026_),
    .Y(_041_)
  );
  NOT _438_ (
    .A(_006_),
    .Y(_043_)
  );
  NAND _439_ (
    .A(_020_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _440_ (
    .A(_044_),
    .B(_251_),
    .Y(_045_)
  );
  NOR _441_ (
    .A(_045_),
    .B(_041_),
    .Y(_046_)
  );
  NOR _442_ (
    .A(_046_),
    .B(_039_),
    .Y(_048_)
  );
  NAND _443_ (
    .A(_048_),
    .B(_056_),
    .Y(_049_)
  );
  NAND _444_ (
    .A(_049_),
    .B(_126_),
    .Y(_051_)
  );
  NOR _445_ (
    .A(_051_),
    .B(_030_),
    .Y(_052_)
  );
  NOR _446_ (
    .A(_052_),
    .B(_010_),
    .Y(_053_)
  );
  NOR _447_ (
    .A(_053_),
    .B(_248_),
    .Y(_050_)
  );
  NOT _448_ (
    .A(_148_),
    .Y(_054_)
  );
  NOR _449_ (
    .A(_245_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _450_ (
    .A(_245_),
    .B(_224_),
    .Y(_057_)
  );
  NAND _451_ (
    .A(_057_),
    .B(_115_),
    .Y(_058_)
  );
  NOR _452_ (
    .A(_058_),
    .B(_055_),
    .Y(_059_)
  );
  NAND _453_ (
    .A(_260_),
    .B(_137_),
    .Y(_060_)
  );
  NOT _454_ (
    .A(_223_),
    .Y(_062_)
  );
  NOR _455_ (
    .A(_260_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _456_ (
    .A(_063_),
    .B(_115_),
    .Y(_064_)
  );
  NAND _457_ (
    .A(_064_),
    .B(_060_),
    .Y(_065_)
  );
  NAND _458_ (
    .A(_065_),
    .B(_258_),
    .Y(_066_)
  );
  NOR _459_ (
    .A(_066_),
    .B(_059_),
    .Y(_067_)
  );
  NOT _460_ (
    .A(_240_),
    .Y(_068_)
  );
  NOR _461_ (
    .A(_260_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _462_ (
    .A(_260_),
    .B(_232_),
    .Y(_070_)
  );
  NAND _463_ (
    .A(_070_),
    .B(_115_),
    .Y(_071_)
  );
  NOR _464_ (
    .A(_071_),
    .B(_069_),
    .Y(_073_)
  );
  NAND _465_ (
    .A(_260_),
    .B(_231_),
    .Y(_074_)
  );
  NOT _466_ (
    .A(_239_),
    .Y(_075_)
  );
  NOR _467_ (
    .A(_260_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _468_ (
    .A(_076_),
    .B(_115_),
    .Y(_077_)
  );
  NAND _469_ (
    .A(_077_),
    .B(_074_),
    .Y(_078_)
  );
  NAND _470_ (
    .A(_078_),
    .B(_246_),
    .Y(_079_)
  );
  NOR _471_ (
    .A(_079_),
    .B(_073_),
    .Y(_080_)
  );
  NOR _472_ (
    .A(_080_),
    .B(_067_),
    .Y(_081_)
  );
  NOR _473_ (
    .A(_081_),
    .B(_126_),
    .Y(_082_)
  );
  NAND _474_ (
    .A(_274_),
    .B(_012_),
    .Y(_084_)
  );
  NAND _475_ (
    .A(_276_),
    .B(_251_),
    .Y(_085_)
  );
  NAND _476_ (
    .A(_085_),
    .B(_084_),
    .Y(_086_)
  );
  NAND _477_ (
    .A(_086_),
    .B(_047_),
    .Y(_087_)
  );
  NAND _478_ (
    .A(_254_),
    .B(_012_),
    .Y(_088_)
  );
  NAND _479_ (
    .A(_256_),
    .B(_251_),
    .Y(_089_)
  );
  NAND _480_ (
    .A(_089_),
    .B(_088_),
    .Y(_090_)
  );
  NAND _481_ (
    .A(_090_),
    .B(_020_),
    .Y(_091_)
  );
  NAND _482_ (
    .A(_091_),
    .B(_087_),
    .Y(_092_)
  );
  NOR _483_ (
    .A(_092_),
    .B(_056_),
    .Y(_093_)
  );
  NOR _484_ (
    .A(_047_),
    .B(_009_),
    .Y(_095_)
  );
  NOT _485_ (
    .A(_029_),
    .Y(_096_)
  );
  NAND _486_ (
    .A(_047_),
    .B(_096_),
    .Y(_097_)
  );
  NAND _487_ (
    .A(_097_),
    .B(_012_),
    .Y(_098_)
  );
  NOR _488_ (
    .A(_098_),
    .B(_095_),
    .Y(_099_)
  );
  NOR _489_ (
    .A(_020_),
    .B(_031_),
    .Y(_100_)
  );
  NOT _490_ (
    .A(_011_),
    .Y(_101_)
  );
  NAND _491_ (
    .A(_020_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _492_ (
    .A(_102_),
    .B(_251_),
    .Y(_103_)
  );
  NOR _493_ (
    .A(_103_),
    .B(_100_),
    .Y(_104_)
  );
  NOR _494_ (
    .A(_104_),
    .B(_099_),
    .Y(_106_)
  );
  NAND _495_ (
    .A(_106_),
    .B(_056_),
    .Y(_107_)
  );
  NAND _496_ (
    .A(_107_),
    .B(_126_),
    .Y(_108_)
  );
  NOR _497_ (
    .A(_108_),
    .B(_093_),
    .Y(_109_)
  );
  NOR _498_ (
    .A(_109_),
    .B(_082_),
    .Y(_110_)
  );
  NOR _499_ (
    .A(_110_),
    .B(_248_),
    .Y(_061_)
  );
  NOT _500_ (
    .A(_179_),
    .Y(_111_)
  );
  NOR _501_ (
    .A(_245_),
    .B(_111_),
    .Y(_112_)
  );
  NAND _502_ (
    .A(_245_),
    .B(_226_),
    .Y(_113_)
  );
  NAND _503_ (
    .A(_113_),
    .B(_115_),
    .Y(_114_)
  );
  NOR _504_ (
    .A(_114_),
    .B(_112_),
    .Y(_116_)
  );
  NAND _505_ (
    .A(_260_),
    .B(_168_),
    .Y(_117_)
  );
  NOT _506_ (
    .A(_225_),
    .Y(_118_)
  );
  NOR _507_ (
    .A(_260_),
    .B(_118_),
    .Y(_119_)
  );
  DFF _508_ (
    .C(clk),
    .D(_000_[0]),
    .Q(nibbleOut[0])
  );
  DFF _509_ (
    .C(clk),
    .D(_000_[1]),
    .Q(nibbleOut[1])
  );
  DFF _510_ (
    .C(clk),
    .D(_000_[2]),
    .Q(nibbleOut[2])
  );
  DFF _511_ (
    .C(clk),
    .D(_000_[3]),
    .Q(nibbleOut[3])
  );
  assign _126_ = sel;
  assign _034_ = reset_L;
  assign _000_[0] = _050_;
  assign _000_[1] = _061_;
  assign _000_[2] = _072_;
  assign _000_[3] = _083_;
  assign _094_ = dataB[0];
  assign _105_ = dataB[16];
  assign _115_ = selB[2];
  assign _137_ = dataB[1];
  assign _148_ = dataB[17];
  assign _168_ = dataB[2];
  assign _179_ = dataB[18];
  assign _200_ = dataB[3];
  assign _211_ = dataB[19];
  assign _221_ = dataB[4];
  assign _222_ = dataB[20];
  assign _223_ = dataB[5];
  assign _224_ = dataB[21];
  assign _225_ = dataB[6];
  assign _226_ = dataB[22];
  assign _227_ = dataB[7];
  assign _228_ = dataB[23];
  assign _229_ = dataB[8];
  assign _230_ = dataB[24];
  assign _231_ = dataB[9];
  assign _232_ = dataB[25];
  assign _233_ = dataB[10];
  assign _234_ = dataB[26];
  assign _235_ = dataB[11];
  assign _236_ = dataB[27];
  assign _237_ = dataB[12];
  assign _238_ = dataB[28];
  assign _239_ = dataB[13];
  assign _240_ = dataB[29];
  assign _241_ = dataB[14];
  assign _242_ = dataB[30];
  assign _243_ = dataB[15];
  assign _244_ = dataB[31];
  assign _245_ = selB[0];
  assign _246_ = selB[1];
  assign _247_ = dataA[0];
  assign _249_ = dataA[16];
  assign _251_ = selA[2];
  assign _254_ = dataA[1];
  assign _256_ = dataA[17];
  assign _259_ = dataA[2];
  assign _261_ = dataA[18];
  assign _264_ = dataA[3];
  assign _266_ = dataA[19];
  assign _269_ = dataA[4];
  assign _271_ = dataA[20];
  assign _274_ = dataA[5];
  assign _276_ = dataA[21];
  assign _279_ = dataA[6];
  assign _281_ = dataA[22];
  assign _284_ = dataA[7];
  assign _001_ = dataA[23];
  assign _004_ = dataA[8];
  assign _006_ = dataA[24];
  assign _009_ = dataA[9];
  assign _011_ = dataA[25];
  assign _014_ = dataA[10];
  assign _016_ = dataA[26];
  assign _019_ = dataA[11];
  assign _021_ = dataA[27];
  assign _024_ = dataA[12];
  assign _026_ = dataA[28];
  assign _029_ = dataA[13];
  assign _031_ = dataA[29];
  assign _035_ = dataA[14];
  assign _037_ = dataA[30];
  assign _040_ = dataA[15];
  assign _042_ = dataA[31];
  assign _047_ = selA[0];
  assign _056_ = selA[1];
endmodule

(* top =  1  *)
(* src = "selector4.v:5" *)
module selector4(temp, DATA_A, DATA_B, sel_A, sel_B, SEL, RESET_L, CLK);
  (* src = "selector4.v:12" *)
  input CLK;
  (* src = "selector4.v:6" *)
  input [31:0] DATA_A;
  (* src = "selector4.v:7" *)
  input [31:0] DATA_B;
  (* src = "selector4.v:5" *)
  wire [3:0] \NIBBLE_OUT[0] ;
  (* src = "selector4.v:5" *)
  wire [3:0] \NIBBLE_OUT[1] ;
  (* src = "selector4.v:5" *)
  wire [3:0] \NIBBLE_OUT[2] ;
  (* src = "selector4.v:5" *)
  wire [3:0] \NIBBLE_OUT[3] ;
  (* src = "selector4.v:11" *)
  input RESET_L;
  (* src = "selector4.v:10" *)
  input [3:0] SEL;
  (* src = "selector4.v:8" *)
  input [11:0] sel_A;
  (* src = "selector4.v:9" *)
  input [11:0] sel_B;
  (* src = "selector4.v:5" *)
  output [15:0] temp;
  (* src = "selector4.v:28" *)
  selector \selectores[0].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(\NIBBLE_OUT[0] ),
    .reset_L(RESET_L),
    .sel(SEL[0]),
    .selA(sel_A[2:0]),
    .selB(sel_B[2:0])
  );
  (* src = "selector4.v:28" *)
  selector \selectores[1].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(\NIBBLE_OUT[1] ),
    .reset_L(RESET_L),
    .sel(SEL[1]),
    .selA(sel_A[5:3]),
    .selB(sel_B[5:3])
  );
  (* src = "selector4.v:28" *)
  selector \selectores[2].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(\NIBBLE_OUT[2] ),
    .reset_L(RESET_L),
    .sel(SEL[2]),
    .selA(sel_A[8:6]),
    .selB(sel_B[8:6])
  );
  (* src = "selector4.v:28" *)
  selector \selectores[3].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(\NIBBLE_OUT[3] ),
    .reset_L(RESET_L),
    .sel(SEL[3]),
    .selA(sel_A[11:9]),
    .selB(sel_B[11:9])
  );
  assign temp = { \NIBBLE_OUT[3] , \NIBBLE_OUT[2] , \NIBBLE_OUT[1] , \NIBBLE_OUT[0]  };
endmodule
