/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "selector4.v:45" *)
module selector(dataA, dataB, selA, selB, sel, reset_L, clk, nibbleOut);
  (* src = "selector4.v:56" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  (* src = "selector4.v:60|<techmap.v>:142" *)
  wire [95:0] _285_;
  (* src = "selector4.v:60|<techmap.v>:142" *)
  wire [95:0] _286_;
  (* src = "selector4.v:60|<techmap.v>:145" *)
  wire [95:0] _287_;
  (* src = "selector4.v:60|<techmap.v>:145" *)
  wire [95:0] _288_;
  (* src = "selector4.v:60|<techmap.v>:145" *)
  wire [95:0] _289_;
  (* src = "selector4.v:60|<techmap.v>:145" *)
  wire [95:0] _290_;
  (* src = "selector4.v:60|<techmap.v>:145" *)
  wire [95:0] _291_;
  (* src = "selector4.v:60|<techmap.v>:145" *)
  wire [95:0] _292_;
  (* src = "selector4.v:60" *)
  wire [3:0] _293_;
  (* src = "selector4.v:52" *)
  input clk;
  (* src = "selector4.v:46" *)
  input [31:0] dataA;
  (* src = "selector4.v:47" *)
  input [31:0] dataB;
  (* src = "selector4.v:53" *)
  output [3:0] nibbleOut;
  (* src = "selector4.v:51" *)
  input reset_L;
  (* src = "selector4.v:50" *)
  input sel;
  (* src = "selector4.v:48" *)
  input [2:0] selA;
  (* src = "selector4.v:49" *)
  input [2:0] selB;
  NAND _294_ (
    .A(_118_),
    .B(_115_),
    .Y(_119_)
  );
  NAND _295_ (
    .A(_119_),
    .B(_257_),
    .Y(_120_)
  );
  NOR _296_ (
    .A(_120_),
    .B(_114_),
    .Y(_121_)
  );
  NOT _297_ (
    .A(_236_),
    .Y(_122_)
  );
  NOR _298_ (
    .A(_259_),
    .B(_122_),
    .Y(_123_)
  );
  NAND _299_ (
    .A(_259_),
    .B(_228_),
    .Y(_124_)
  );
  NAND _300_ (
    .A(_124_),
    .B(_035_),
    .Y(_127_)
  );
  NOR _301_ (
    .A(_127_),
    .B(_123_),
    .Y(_128_)
  );
  NAND _302_ (
    .A(_259_),
    .B(_227_),
    .Y(_129_)
  );
  NOT _303_ (
    .A(_235_),
    .Y(_130_)
  );
  NOR _304_ (
    .A(_259_),
    .B(_130_),
    .Y(_131_)
  );
  NOR _305_ (
    .A(_131_),
    .B(_035_),
    .Y(_132_)
  );
  NAND _306_ (
    .A(_132_),
    .B(_129_),
    .Y(_133_)
  );
  NAND _307_ (
    .A(_133_),
    .B(_240_),
    .Y(_134_)
  );
  NOR _308_ (
    .A(_134_),
    .B(_128_),
    .Y(_135_)
  );
  NOR _309_ (
    .A(_135_),
    .B(_121_),
    .Y(_136_)
  );
  NOR _310_ (
    .A(_136_),
    .B(_125_),
    .Y(_138_)
  );
  NAND _311_ (
    .A(_024_),
    .B(_012_),
    .Y(_139_)
  );
  NAND _312_ (
    .A(_026_),
    .B(_243_),
    .Y(_140_)
  );
  NAND _313_ (
    .A(_140_),
    .B(_139_),
    .Y(_141_)
  );
  NAND _314_ (
    .A(_141_),
    .B(_037_),
    .Y(_142_)
  );
  NAND _315_ (
    .A(_003_),
    .B(_012_),
    .Y(_143_)
  );
  NAND _316_ (
    .A(_005_),
    .B(_243_),
    .Y(_144_)
  );
  NAND _317_ (
    .A(_144_),
    .B(_143_),
    .Y(_145_)
  );
  NAND _318_ (
    .A(_145_),
    .B(_022_),
    .Y(_146_)
  );
  NAND _319_ (
    .A(_146_),
    .B(_142_),
    .Y(_147_)
  );
  NOR _320_ (
    .A(_147_),
    .B(_039_),
    .Y(_148_)
  );
  NOR _321_ (
    .A(_037_),
    .B(_246_),
    .Y(_149_)
  );
  NOT _322_ (
    .A(_266_),
    .Y(_150_)
  );
  NAND _323_ (
    .A(_037_),
    .B(_150_),
    .Y(_151_)
  );
  NAND _324_ (
    .A(_151_),
    .B(_012_),
    .Y(_152_)
  );
  NOR _325_ (
    .A(_152_),
    .B(_149_),
    .Y(_153_)
  );
  NOR _326_ (
    .A(_022_),
    .B(_268_),
    .Y(_154_)
  );
  NOT _327_ (
    .A(_248_),
    .Y(_155_)
  );
  NAND _328_ (
    .A(_022_),
    .B(_155_),
    .Y(_156_)
  );
  NAND _329_ (
    .A(_156_),
    .B(_243_),
    .Y(_157_)
  );
  NOR _330_ (
    .A(_157_),
    .B(_154_),
    .Y(_159_)
  );
  NOR _331_ (
    .A(_159_),
    .B(_153_),
    .Y(_160_)
  );
  NAND _332_ (
    .A(_160_),
    .B(_039_),
    .Y(_161_)
  );
  NAND _333_ (
    .A(_161_),
    .B(_125_),
    .Y(_162_)
  );
  NOR _334_ (
    .A(_162_),
    .B(_148_),
    .Y(_163_)
  );
  NOR _335_ (
    .A(_163_),
    .B(_138_),
    .Y(_164_)
  );
  NOR _336_ (
    .A(_164_),
    .B(_247_),
    .Y(_053_)
  );
  NOT _337_ (
    .A(_137_),
    .Y(_165_)
  );
  NOR _338_ (
    .A(_239_),
    .B(_165_),
    .Y(_166_)
  );
  NAND _339_ (
    .A(_239_),
    .B(_222_),
    .Y(_167_)
  );
  NAND _340_ (
    .A(_167_),
    .B(_035_),
    .Y(_169_)
  );
  NOR _341_ (
    .A(_169_),
    .B(_166_),
    .Y(_170_)
  );
  NAND _342_ (
    .A(_259_),
    .B(_126_),
    .Y(_171_)
  );
  NOT _343_ (
    .A(_221_),
    .Y(_172_)
  );
  NOR _344_ (
    .A(_259_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _345_ (
    .A(_173_),
    .B(_035_),
    .Y(_174_)
  );
  NAND _346_ (
    .A(_174_),
    .B(_171_),
    .Y(_175_)
  );
  NAND _347_ (
    .A(_175_),
    .B(_257_),
    .Y(_176_)
  );
  NOR _348_ (
    .A(_176_),
    .B(_170_),
    .Y(_177_)
  );
  NOT _349_ (
    .A(_230_),
    .Y(_178_)
  );
  NOR _350_ (
    .A(_239_),
    .B(_178_),
    .Y(_179_)
  );
  NAND _351_ (
    .A(_239_),
    .B(_238_),
    .Y(_180_)
  );
  NAND _352_ (
    .A(_180_),
    .B(_035_),
    .Y(_181_)
  );
  NOR _353_ (
    .A(_181_),
    .B(_179_),
    .Y(_182_)
  );
  NAND _354_ (
    .A(_259_),
    .B(_229_),
    .Y(_183_)
  );
  NOT _355_ (
    .A(_237_),
    .Y(_184_)
  );
  NOR _356_ (
    .A(_259_),
    .B(_184_),
    .Y(_185_)
  );
  NOR _357_ (
    .A(_185_),
    .B(_035_),
    .Y(_186_)
  );
  NAND _358_ (
    .A(_186_),
    .B(_183_),
    .Y(_187_)
  );
  NAND _359_ (
    .A(_187_),
    .B(_240_),
    .Y(_188_)
  );
  NOR _360_ (
    .A(_188_),
    .B(_182_),
    .Y(_190_)
  );
  NOR _361_ (
    .A(_190_),
    .B(_177_),
    .Y(_191_)
  );
  NOR _362_ (
    .A(_191_),
    .B(_125_),
    .Y(_192_)
  );
  NAND _363_ (
    .A(_029_),
    .B(_012_),
    .Y(_193_)
  );
  NAND _364_ (
    .A(_031_),
    .B(_243_),
    .Y(_194_)
  );
  NAND _365_ (
    .A(_194_),
    .B(_193_),
    .Y(_195_)
  );
  NAND _366_ (
    .A(_195_),
    .B(_037_),
    .Y(_196_)
  );
  NAND _367_ (
    .A(_008_),
    .B(_012_),
    .Y(_197_)
  );
  NAND _368_ (
    .A(_010_),
    .B(_243_),
    .Y(_198_)
  );
  NAND _369_ (
    .A(_198_),
    .B(_197_),
    .Y(_199_)
  );
  NAND _370_ (
    .A(_199_),
    .B(_022_),
    .Y(_201_)
  );
  NAND _371_ (
    .A(_201_),
    .B(_196_),
    .Y(_202_)
  );
  NOR _372_ (
    .A(_202_),
    .B(_039_),
    .Y(_203_)
  );
  NOR _373_ (
    .A(_037_),
    .B(_251_),
    .Y(_204_)
  );
  NOT _374_ (
    .A(_271_),
    .Y(_205_)
  );
  NAND _375_ (
    .A(_037_),
    .B(_205_),
    .Y(_206_)
  );
  NAND _376_ (
    .A(_206_),
    .B(_012_),
    .Y(_207_)
  );
  NOR _377_ (
    .A(_207_),
    .B(_204_),
    .Y(_208_)
  );
  NOR _378_ (
    .A(_022_),
    .B(_273_),
    .Y(_209_)
  );
  NOT _379_ (
    .A(_253_),
    .Y(_210_)
  );
  NAND _380_ (
    .A(_022_),
    .B(_210_),
    .Y(_211_)
  );
  NAND _381_ (
    .A(_211_),
    .B(_243_),
    .Y(_212_)
  );
  NOR _382_ (
    .A(_212_),
    .B(_209_),
    .Y(_213_)
  );
  NOR _383_ (
    .A(_213_),
    .B(_208_),
    .Y(_214_)
  );
  NAND _384_ (
    .A(_214_),
    .B(_039_),
    .Y(_215_)
  );
  NAND _385_ (
    .A(_215_),
    .B(_125_),
    .Y(_216_)
  );
  NOR _386_ (
    .A(_216_),
    .B(_203_),
    .Y(_217_)
  );
  NOR _387_ (
    .A(_217_),
    .B(_192_),
    .Y(_218_)
  );
  NOR _388_ (
    .A(_218_),
    .B(_247_),
    .Y(_055_)
  );
  NOT _389_ (
    .A(_048_),
    .Y(_247_)
  );
  NOT _390_ (
    .A(_018_),
    .Y(_249_)
  );
  NOR _391_ (
    .A(_239_),
    .B(_249_),
    .Y(_250_)
  );
  NAND _392_ (
    .A(_239_),
    .B(_168_),
    .Y(_252_)
  );
  NAND _393_ (
    .A(_252_),
    .B(_035_),
    .Y(_254_)
  );
  NOR _394_ (
    .A(_254_),
    .B(_250_),
    .Y(_255_)
  );
  NOT _395_ (
    .A(_240_),
    .Y(_257_)
  );
  NOT _396_ (
    .A(_239_),
    .Y(_259_)
  );
  NAND _397_ (
    .A(_259_),
    .B(_001_),
    .Y(_260_)
  );
  NOT _398_ (
    .A(_158_),
    .Y(_262_)
  );
  NOR _399_ (
    .A(_259_),
    .B(_262_),
    .Y(_264_)
  );
  NOR _400_ (
    .A(_264_),
    .B(_035_),
    .Y(_265_)
  );
  NAND _401_ (
    .A(_265_),
    .B(_260_),
    .Y(_267_)
  );
  NAND _402_ (
    .A(_267_),
    .B(_257_),
    .Y(_269_)
  );
  NOR _403_ (
    .A(_269_),
    .B(_255_),
    .Y(_270_)
  );
  NOT _404_ (
    .A(_224_),
    .Y(_272_)
  );
  NOR _405_ (
    .A(_239_),
    .B(_272_),
    .Y(_274_)
  );
  NAND _406_ (
    .A(_239_),
    .B(_232_),
    .Y(_275_)
  );
  NAND _407_ (
    .A(_275_),
    .B(_035_),
    .Y(_277_)
  );
  NOR _408_ (
    .A(_277_),
    .B(_274_),
    .Y(_279_)
  );
  NAND _409_ (
    .A(_259_),
    .B(_223_),
    .Y(_280_)
  );
  NOT _410_ (
    .A(_231_),
    .Y(_282_)
  );
  NOR _411_ (
    .A(_259_),
    .B(_282_),
    .Y(_284_)
  );
  NOR _412_ (
    .A(_284_),
    .B(_035_),
    .Y(_002_)
  );
  NAND _413_ (
    .A(_002_),
    .B(_280_),
    .Y(_004_)
  );
  NAND _414_ (
    .A(_004_),
    .B(_240_),
    .Y(_006_)
  );
  NOR _415_ (
    .A(_006_),
    .B(_279_),
    .Y(_007_)
  );
  NOR _416_ (
    .A(_007_),
    .B(_270_),
    .Y(_009_)
  );
  NOR _417_ (
    .A(_009_),
    .B(_125_),
    .Y(_011_)
  );
  NOT _418_ (
    .A(_243_),
    .Y(_012_)
  );
  NAND _419_ (
    .A(_256_),
    .B(_012_),
    .Y(_014_)
  );
  NAND _420_ (
    .A(_258_),
    .B(_243_),
    .Y(_016_)
  );
  NAND _421_ (
    .A(_016_),
    .B(_014_),
    .Y(_017_)
  );
  NAND _422_ (
    .A(_017_),
    .B(_037_),
    .Y(_020_)
  );
  NOT _423_ (
    .A(_037_),
    .Y(_022_)
  );
  NAND _424_ (
    .A(_012_),
    .B(_241_),
    .Y(_023_)
  );
  NAND _425_ (
    .A(_243_),
    .B(_242_),
    .Y(_025_)
  );
  NAND _426_ (
    .A(_025_),
    .B(_023_),
    .Y(_027_)
  );
  NAND _427_ (
    .A(_027_),
    .B(_022_),
    .Y(_028_)
  );
  NAND _428_ (
    .A(_028_),
    .B(_020_),
    .Y(_030_)
  );
  NOR _429_ (
    .A(_030_),
    .B(_057_),
    .Y(_032_)
  );
  NOR _430_ (
    .A(_037_),
    .B(_276_),
    .Y(_033_)
  );
  NOR _431_ (
    .A(_022_),
    .B(_013_),
    .Y(_034_)
  );
  NOR _432_ (
    .A(_034_),
    .B(_033_),
    .Y(_036_)
  );
  NAND _433_ (
    .A(_036_),
    .B(_012_),
    .Y(_038_)
  );
  NOT _434_ (
    .A(_057_),
    .Y(_039_)
  );
  NOR _435_ (
    .A(_022_),
    .B(_015_),
    .Y(_040_)
  );
  NOT _436_ (
    .A(_278_),
    .Y(_041_)
  );
  NAND _437_ (
    .A(_022_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _438_ (
    .A(_042_),
    .B(_243_),
    .Y(_043_)
  );
  NOR _439_ (
    .A(_043_),
    .B(_040_),
    .Y(_044_)
  );
  NOR _440_ (
    .A(_044_),
    .B(_039_),
    .Y(_045_)
  );
  NAND _441_ (
    .A(_045_),
    .B(_038_),
    .Y(_046_)
  );
  NAND _442_ (
    .A(_046_),
    .B(_125_),
    .Y(_047_)
  );
  NOR _443_ (
    .A(_047_),
    .B(_032_),
    .Y(_049_)
  );
  NOR _444_ (
    .A(_049_),
    .B(_011_),
    .Y(_051_)
  );
  NOR _445_ (
    .A(_051_),
    .B(_247_),
    .Y(_050_)
  );
  NOT _446_ (
    .A(_073_),
    .Y(_054_)
  );
  NOR _447_ (
    .A(_239_),
    .B(_054_),
    .Y(_056_)
  );
  NAND _448_ (
    .A(_239_),
    .B(_200_),
    .Y(_058_)
  );
  NAND _449_ (
    .A(_058_),
    .B(_035_),
    .Y(_059_)
  );
  NOR _450_ (
    .A(_059_),
    .B(_056_),
    .Y(_060_)
  );
  NAND _451_ (
    .A(_259_),
    .B(_062_),
    .Y(_061_)
  );
  NOT _452_ (
    .A(_189_),
    .Y(_063_)
  );
  NOR _453_ (
    .A(_259_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _454_ (
    .A(_064_),
    .B(_035_),
    .Y(_065_)
  );
  NAND _455_ (
    .A(_065_),
    .B(_061_),
    .Y(_066_)
  );
  NAND _456_ (
    .A(_066_),
    .B(_257_),
    .Y(_067_)
  );
  NOR _457_ (
    .A(_067_),
    .B(_060_),
    .Y(_068_)
  );
  NOT _458_ (
    .A(_234_),
    .Y(_069_)
  );
  NOR _459_ (
    .A(_259_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _460_ (
    .A(_259_),
    .B(_226_),
    .Y(_071_)
  );
  NAND _461_ (
    .A(_071_),
    .B(_035_),
    .Y(_072_)
  );
  NOR _462_ (
    .A(_072_),
    .B(_070_),
    .Y(_074_)
  );
  NAND _463_ (
    .A(_259_),
    .B(_225_),
    .Y(_075_)
  );
  NOT _464_ (
    .A(_233_),
    .Y(_076_)
  );
  NOR _465_ (
    .A(_259_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _466_ (
    .A(_077_),
    .B(_035_),
    .Y(_078_)
  );
  NAND _467_ (
    .A(_078_),
    .B(_075_),
    .Y(_079_)
  );
  NAND _468_ (
    .A(_079_),
    .B(_240_),
    .Y(_080_)
  );
  NOR _469_ (
    .A(_080_),
    .B(_074_),
    .Y(_081_)
  );
  NOR _470_ (
    .A(_081_),
    .B(_068_),
    .Y(_082_)
  );
  NOR _471_ (
    .A(_082_),
    .B(_125_),
    .Y(_083_)
  );
  NAND _472_ (
    .A(_261_),
    .B(_012_),
    .Y(_084_)
  );
  NAND _473_ (
    .A(_263_),
    .B(_243_),
    .Y(_085_)
  );
  NAND _474_ (
    .A(_085_),
    .B(_084_),
    .Y(_086_)
  );
  NAND _475_ (
    .A(_086_),
    .B(_037_),
    .Y(_087_)
  );
  NAND _476_ (
    .A(_244_),
    .B(_012_),
    .Y(_088_)
  );
  NAND _477_ (
    .A(_245_),
    .B(_243_),
    .Y(_089_)
  );
  NAND _478_ (
    .A(_089_),
    .B(_088_),
    .Y(_090_)
  );
  NAND _479_ (
    .A(_090_),
    .B(_022_),
    .Y(_091_)
  );
  NAND _480_ (
    .A(_091_),
    .B(_087_),
    .Y(_092_)
  );
  NOR _481_ (
    .A(_092_),
    .B(_057_),
    .Y(_093_)
  );
  NOR _482_ (
    .A(_037_),
    .B(_281_),
    .Y(_095_)
  );
  NOR _483_ (
    .A(_022_),
    .B(_019_),
    .Y(_096_)
  );
  NOR _484_ (
    .A(_096_),
    .B(_095_),
    .Y(_097_)
  );
  NAND _485_ (
    .A(_097_),
    .B(_012_),
    .Y(_098_)
  );
  NOR _486_ (
    .A(_022_),
    .B(_021_),
    .Y(_099_)
  );
  NOT _487_ (
    .A(_283_),
    .Y(_100_)
  );
  NAND _488_ (
    .A(_022_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _489_ (
    .A(_101_),
    .B(_243_),
    .Y(_102_)
  );
  NOR _490_ (
    .A(_102_),
    .B(_099_),
    .Y(_103_)
  );
  NOR _491_ (
    .A(_103_),
    .B(_039_),
    .Y(_104_)
  );
  NAND _492_ (
    .A(_104_),
    .B(_098_),
    .Y(_106_)
  );
  NAND _493_ (
    .A(_106_),
    .B(_125_),
    .Y(_107_)
  );
  NOR _494_ (
    .A(_107_),
    .B(_093_),
    .Y(_108_)
  );
  NOR _495_ (
    .A(_108_),
    .B(_083_),
    .Y(_109_)
  );
  NOR _496_ (
    .A(_109_),
    .B(_247_),
    .Y(_052_)
  );
  NOT _497_ (
    .A(_105_),
    .Y(_110_)
  );
  NOR _498_ (
    .A(_239_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _499_ (
    .A(_239_),
    .B(_220_),
    .Y(_112_)
  );
  NAND _500_ (
    .A(_112_),
    .B(_035_),
    .Y(_113_)
  );
  NOR _501_ (
    .A(_113_),
    .B(_111_),
    .Y(_114_)
  );
  NAND _502_ (
    .A(_259_),
    .B(_094_),
    .Y(_115_)
  );
  NOT _503_ (
    .A(_219_),
    .Y(_116_)
  );
  NOR _504_ (
    .A(_259_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _505_ (
    .A(_117_),
    .B(_035_),
    .Y(_118_)
  );
  DFF _506_ (
    .C(clk),
    .D(_000_[0]),
    .Q(nibbleOut[0])
  );
  DFF _507_ (
    .C(clk),
    .D(_000_[1]),
    .Q(nibbleOut[1])
  );
  DFF _508_ (
    .C(clk),
    .D(_000_[2]),
    .Q(nibbleOut[2])
  );
  DFF _509_ (
    .C(clk),
    .D(_000_[3]),
    .Q(nibbleOut[3])
  );
  assign _125_ = sel;
  assign _001_ = dataB[0];
  assign _018_ = dataB[16];
  assign _035_ = selB[2];
  assign _062_ = dataB[1];
  assign _073_ = dataB[17];
  assign _094_ = dataB[2];
  assign _105_ = dataB[18];
  assign _126_ = dataB[3];
  assign _137_ = dataB[19];
  assign _158_ = dataB[4];
  assign _168_ = dataB[20];
  assign _189_ = dataB[5];
  assign _200_ = dataB[21];
  assign _219_ = dataB[6];
  assign _220_ = dataB[22];
  assign _221_ = dataB[7];
  assign _222_ = dataB[23];
  assign _223_ = dataB[8];
  assign _224_ = dataB[24];
  assign _225_ = dataB[9];
  assign _226_ = dataB[25];
  assign _227_ = dataB[10];
  assign _228_ = dataB[26];
  assign _229_ = dataB[11];
  assign _230_ = dataB[27];
  assign _231_ = dataB[12];
  assign _232_ = dataB[28];
  assign _233_ = dataB[13];
  assign _234_ = dataB[29];
  assign _235_ = dataB[14];
  assign _236_ = dataB[30];
  assign _237_ = dataB[15];
  assign _238_ = dataB[31];
  assign _239_ = selB[0];
  assign _240_ = selB[1];
  assign _241_ = dataA[0];
  assign _242_ = dataA[16];
  assign _243_ = selA[2];
  assign _244_ = dataA[1];
  assign _245_ = dataA[17];
  assign _246_ = dataA[2];
  assign _248_ = dataA[18];
  assign _251_ = dataA[3];
  assign _253_ = dataA[19];
  assign _256_ = dataA[4];
  assign _258_ = dataA[20];
  assign _261_ = dataA[5];
  assign _263_ = dataA[21];
  assign _266_ = dataA[6];
  assign _268_ = dataA[22];
  assign _271_ = dataA[7];
  assign _273_ = dataA[23];
  assign _276_ = dataA[8];
  assign _278_ = dataA[24];
  assign _281_ = dataA[9];
  assign _283_ = dataA[25];
  assign _003_ = dataA[10];
  assign _005_ = dataA[26];
  assign _008_ = dataA[11];
  assign _010_ = dataA[27];
  assign _013_ = dataA[12];
  assign _015_ = dataA[28];
  assign _019_ = dataA[13];
  assign _021_ = dataA[29];
  assign _024_ = dataA[14];
  assign _026_ = dataA[30];
  assign _029_ = dataA[15];
  assign _031_ = dataA[31];
  assign _037_ = selA[0];
  assign _048_ = reset_L;
  assign _000_[0] = _050_;
  assign _000_[1] = _052_;
  assign _000_[2] = _053_;
  assign _000_[3] = _055_;
  assign _057_ = selA[1];
endmodule

(* top =  1  *)
(* src = "selector4.v:5" *)
module selector4(NIBBLE_OUT, DATA_A, DATA_B, sel_A, sel_B, SEL, RESET_L, CLK);
  (* src = "selector4.v:12" *)
  input CLK;
  (* src = "selector4.v:6" *)
  input [31:0] DATA_A;
  (* src = "selector4.v:7" *)
  input [31:0] DATA_B;
  (* src = "selector4.v:5" *)
  output [15:0] NIBBLE_OUT;
  (* src = "selector4.v:11" *)
  input RESET_L;
  (* src = "selector4.v:10" *)
  input [3:0] SEL;
  (* src = "selector4.v:8" *)
  input [11:0] sel_A;
  (* src = "selector4.v:9" *)
  input [11:0] sel_B;
  (* src = "selector4.v:5" *)
  wire [3:0] \temp_nibble[0] ;
  (* src = "selector4.v:5" *)
  wire [3:0] \temp_nibble[1] ;
  (* src = "selector4.v:5" *)
  wire [3:0] \temp_nibble[2] ;
  (* src = "selector4.v:5" *)
  wire [3:0] \temp_nibble[3] ;
  (* src = "selector4.v:28" *)
  selector \selectores[0].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(\temp_nibble[0] ),
    .reset_L(RESET_L),
    .sel(SEL[0]),
    .selA(sel_A[2:0]),
    .selB(sel_B[2:0])
  );
  (* src = "selector4.v:28" *)
  selector \selectores[1].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(\temp_nibble[1] ),
    .reset_L(RESET_L),
    .sel(SEL[1]),
    .selA(sel_A[5:3]),
    .selB(sel_B[5:3])
  );
  (* src = "selector4.v:28" *)
  selector \selectores[2].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(\temp_nibble[2] ),
    .reset_L(RESET_L),
    .sel(SEL[2]),
    .selA(sel_A[8:6]),
    .selB(sel_B[8:6])
  );
  (* src = "selector4.v:28" *)
  selector \selectores[3].seli  (
    .clk(CLK),
    .dataA(DATA_A),
    .dataB(DATA_B),
    .nibbleOut(\temp_nibble[3] ),
    .reset_L(RESET_L),
    .sel(SEL[3]),
    .selA(sel_A[11:9]),
    .selB(sel_B[11:9])
  );
  assign NIBBLE_OUT = { \temp_nibble[3] , \temp_nibble[2] , \temp_nibble[1] , \temp_nibble[0]  };
endmodule
